spring:
  application:
    name: avaliacao
  profiles:
    active: default

  output:
    ansi:
      enabled: always
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:releases}
    username: ${DATASOURCE_USERNAME:user}
    password: ${DATASOURCE_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

springdoc:
  override-with-generic-response: false
  swagger-ui:
    path: /swagger-ui.html
